# Generated by Django 2.0.1 on 2018-01-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nowa', '0002_auto_20180113_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='piosenka',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
