# Generated by Django 2.0.1 on 2018-01-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpio',
            name='bolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gpio',
            name='lista',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='gpio',
            name='opis',
            field=models.CharField(default='', max_length=250),
        ),
    ]
